version: "2.1"
services:
    firefox:
        image: selenium/node-firefox:3.4.0
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - hub
        environment:
            HUB_HOST: hub

    chrome:
        image: selenium/node-chrome:3.4.0
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - hub
        environment:
            HUB_HOST: hub

    hub:
        image: selenium/hub:3.4.0
        ports:
            - "4444:4444"
